In [1]:
import numpy as np

# Creating Arrays

In [2]:
mylist=[1,2,3]
x=np.array(mylist)
x

array([1, 2, 3])

In [3]:
m=np.array([[1,2,3],[4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
m.shape

(2, 3)

In [5]:
n=np.arange(0,30,2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [7]:
n=n.reshape(3,5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [8]:
o=np.linspace(0,4,9)
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [9]:
o.reshape(3,3)

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [12]:
o.resize(3,3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [13]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
y=np.array([4,5,6])
np.diag(y)  #places elements diagonal

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [21]:
# repeated arrays
np.array([1,2,3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [23]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [25]:
p=np.ones((2,3))
p

array([[1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.vstack([p,p*2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [27]:
np.hstack([p,p*2])

array([[1., 1., 1., 2., 2., 2.],
       [1., 1., 1., 2., 2., 2.]])

# Operations

In [28]:
x+y

array([5, 7, 9])

In [29]:
x.dot(y)

32

In [31]:
z=np.array([y,y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [32]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [33]:
z.dtype

dtype('int64')

In [34]:
z=z.astype('f')
z.dtype

dtype('float32')

## Indexing and slicing

In [36]:
s=np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [38]:
s[1:5],s[-4:]

(array([ 1,  4,  9, 16]), array([ 81, 100, 121, 144]))

In [41]:
s[-5::-2]

array([64, 36, 16,  4,  0])

In [42]:
r=np.arange(36)
r.resize((6,6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [43]:
r[2,2]

14

In [44]:
r[3,3:6]

array([21, 22, 23])

In [47]:
r[:2,:-1]   # all the columns except for last

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [48]:
r[-1,::2]

array([30, 32, 34])

In [49]:
r[r>30]

array([31, 32, 33, 34, 35])

In [50]:
r2=r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [51]:
r2[:]=0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [52]:
r  # Values here are also updated

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [54]:
r_copy=r.copy()   # Values are not changed in the original array
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [55]:
r_copy[:]=0
r_copy

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [56]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

## Iterating over arrays

In [57]:
test=np.random.randint(0,10,(4,3))
test

array([[6, 1, 5],
       [2, 0, 5],
       [5, 5, 4],
       [1, 6, 2]])

In [58]:
for row in test:
    print(row)

[6 1 5]
[2 0 5]
[5 5 4]
[1 6 2]


In [59]:
for i,row in enumerate(test):
    print('row',i,'is',row)

row 0 is [6 1 5]
row 1 is [2 0 5]
row 2 is [5 5 4]
row 3 is [1 6 2]


In [60]:
test2=test**2
test2

array([[36,  1, 25],
       [ 4,  0, 25],
       [25, 25, 16],
       [ 1, 36,  4]])

In [61]:
for i,j in zip(test,test2):
    print(i,'+',j,'=',i+j)

[6 1 5] + [36  1 25] = [42  2 30]
[2 0 5] + [ 4  0 25] = [ 6  0 30]
[5 5 4] + [25 25 16] = [30 30 20]
[1 6 2] + [ 1 36  4] = [ 2 42  6]
